### PR TITLE
feat: Add dedicated Test Case for Open the left menu when hover on hamburger menu icon  - MEED-1807 - Meeds-io/meeds#755

### PR DESCRIPTION
**Pull request by SaraBoutej**

### CODE REVIEW

**Comment by AzmiTouil** [comment]
Test in progress https://ci.exoplatform.org/view/PLF%20-%20QA%20UI/job/exo-qa-ui/job/qa-ui-auto-meeds/474/

**Comment by boubaker** [comment]
Another Test in progress after PR for stabilization :  https://ci.exoplatform.org/view/PLF%20-%20QA%20UI/job/exo-qa-ui/job/qa-ui-auto-meeds/476/console

**Comment by boubaker** [comment]
A new execution is in progress : https://ci.exoplatform.org/view/PLF%20-%20QA%20UI/job/exo-qa-ui/job/qa-ui-auto-meeds/477/console

**Review by boubaker — APPROVED** [review]
Seems ok now

**Pull request merged**
